services:
  metahkg-images:
    container_name: metahkg-images
    build:
      context: ../
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - ${port}:${port}
    environment:
      port: ${port}
      DB_URI: mongodb://${MONGO_USER}:${MONGO_PASSWORD}@metahkg-images-mongo:${MONGO_PORT}
      proxy_host: ${proxy_host}
      proxy_port: ${proxy_port}
      proxy_auth: ${proxy_auth}
      no_proxy: ${no_proxy}
    depends_on:
      - metahkg-images-mongo
      - metahkg-images-tor
    networks:
      - metahkg-images-network
  metahkg-images-tor:
    image: peterdavehello/tor-socks-proxy
    container_name: metahkg-images-tor
    restart: always
    networks:
      - metahkg-images-network
  metahkg-images-mongo:
    container_name: metahkg-images-mongo
    image: mongo
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}
    command: mongod --auth --port=${MONGO_PORT} --bind_ip_all
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: images
    volumes:
      - ./data:/data/db
    networks:
      - metahkg-images-network
networks:
  metahkg-images-network:
    driver: bridge
